version: '3.9'

services:
    app:
        image: postgres:latest
        container_name: spendwise-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_DB=spendwise
        volumes:
            - spendwise-postgres-data:/var/lib/postgresql/data

volumes:
    spendwise-postgres-data:
